# Generated by Django 4.0.4 on 2023-01-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_food_expiry_alter_profile_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
